import { AlertOutlined, DeploymentUnitOutlined } from '@ant-design/icons'
import { useQuery } from '@tanstack/react-query'
import { Alert, Card, Empty, Layout, Menu, Space, Table, Tag, Typography } from 'antd'
import axios from 'axios'
import dayjs from 'dayjs'
import { Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import './styles.css'
const api=axios.create({baseURL:'/api/v1',timeout:10000})
const colors:Record<string,string>={critical:'red',warning:'orange',info:'blue',open:'red',resolved:'green'}
function Incidents(){const navigate=useNavigate();const query=useQuery({queryKey:['incidents'],queryFn:async()=> (await api.get('/incidents')).data});const items=query.data?.items||[];return <Space direction="vertical" size={16} style={{width:'100%'}}><Typography.Title level={3}>告警事件</Typography.Title>{query.error&&<Alert type="error" showIcon message="加载失败" description={String(query.error)}/>}<Card><Table rowKey="id" loading={query.isLoading} dataSource={items} locale={{emptyText:<Empty description="尚无事件"/>}} onRow={(row:any)=>({onClick:()=>navigate(`/incidents/${row.id}`),style:{cursor:'pointer'}})} columns={[{title:'ID',dataIndex:'id',width:80},{title:'事件',dataIndex:'title'},{title:'服务',render:(_:unknown,row:any)=>String(row.labels?.service||'-')},{title:'级别',dataIndex:'severity',render:(v:string)=><Tag color={colors[v]}>{v}</Tag>},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={colors[v]}>{v}</Tag>},{title:'告警数',dataIndex:'alert_count'},{title:'最后发生',dataIndex:'last_seen_at',render:(v:string)=>dayjs(v).format('YYYY-MM-DD HH:mm:ss')}]}/></Card></Space>}
function Detail(){const id=location.pathname.split('/').pop();const q=useQuery({queryKey:['incident',id],queryFn:async()=> (await api.get(`/incidents/${id}`)).data});if(q.isLoading)return <Card>加载中...</Card>;if(q.error)return <Alert type="error" message="详情加载失败"/>;const d=q.data;return <Space direction="vertical" style={{width:'100%'}}><Link to="/incidents">← 返回</Link><Typography.Title level={3}>{d.title}</Typography.Title><Card title="事件信息"><pre>{JSON.stringify({status:d.status,severity:d.severity,labels:d.labels,alert_count:d.alert_count},null,2)}</pre></Card><Card title="关联告警"><pre>{JSON.stringify(d.alerts,null,2)}</pre></Card><Card title="AI 分析"><Empty description="Worker 已接入，证据采集与模型分析下一步启用"/></Card></Space>}
export default function App(){return <Layout className="shell"><Layout.Sider width={220}><div className="brand"><DeploymentUnitOutlined/> AIOps Console</div><Menu theme="dark" items={[{key:'incidents',icon:<AlertOutlined/>,label:<Link to="/incidents">告警事件</Link>}]}/></Layout.Sider><Layout><Layout.Header className="header"><Typography.Title level={4}>AI 运维事件中心</Typography.Title></Layout.Header><Layout.Content className="content"><Routes><Route path="/incidents" element={<Incidents/>}/><Route path="/incidents/:id" element={<Detail/>}/><Route path="*" element={<Navigate to="/incidents" replace/>}/></Routes></Layout.Content></Layout></Layout>}
